### ISSUE TITLE
Add maintainers page to main meu

### ISSUE THREAD

**Issue by isuruAb** [CodeLanka/codelanka.github.io#3]
**Actual Behaviour**

There is no maintainers menu item

**Expected Behaviour**

Add maintainers page to the main menu.
It should look like this.

<img width="1268" alt="screen shot 2018-05-19 at 9 11 26 pm" src="https://user-images.githubusercontent.com/7692626/40270349-5ddb60ea-5ba9-11e8-8a25-cf823ec76513.png">

**Would you like to work on the issue?**

anyone can get

**Comment by naveentherocker** [comment]
Claiming
