### ISSUE TITLE
Remove Our Philantrophist section and Blog section from the home page.

### ISSUE THREAD

**Issue by isuruAb** [CodeLanka/codelanka.github.io#4]
**Actual Behaviour**

There are Blog and Philanthropist sections on the homepage

**Expected Behaviour**

Remove Our Philanthropist section and Blog section from the home page.

**Would you like to work on the issue?**

anyone can get

**Comment by sathiraumesh** [comment]
Is this issue still open

**Comment by isuruAb** [comment]
@sathiraumesh  Blog section is still there.Please check this link http://codelanka.github.io/. We dont need a blog section because we have a separate page for blog
